# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import test


class army_selection(object):
    def setupUi(self, armyWindow):
        armyWindow.setObjectName("armyWindow")
        armyWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(armyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton = QtWidgets.QPushButton(armyWindow)
        self.pushButton.setGeometry(QtCore.QRect(80, 80, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.switch_screen())

        armyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(armyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        armyWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(armyWindow)
        self.statusbar.setObjectName("statusbar")
        armyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(armyWindow)
        QtCore.QMetaObject.connectSlotsByName(armyWindow)

    def switch_screen(self):
        MainWindow = QtWidgets.QMainWindow()
        ui = test.Ui_MainWindow()
        ui.setupUi(MainWindow)
        try:
            MainWindow.show()
            print("hola")
        except Exception as e:
            print(e)
            
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
#
#
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = test.Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
