# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.playerA_add_turn = QtWidgets.QPushButton(self.centralwidget)
        self.playerA_add_turn.setGeometry(QtCore.QRect(170, 120, 61, 61))
        self.playerA_add_turn.setObjectName("playerA_add_turn")
        self.playerA_subtract_turn = QtWidgets.QPushButton(self.centralwidget)
        self.playerA_subtract_turn.setGeometry(QtCore.QRect(30, 120, 61, 61))
        self.playerA_subtract_turn.setObjectName("playerA_subtract_turn")
        self.current_battleround_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.current_battleround_text.setGeometry(QtCore.QRect(380, 20, 261, 41))
        self.current_battleround_text.setObjectName("current_battleround_text")
        self.current_battleround_number = QtWidgets.QTextEdit(self.centralwidget)
        self.current_battleround_number.setGeometry(QtCore.QRect(480, 60, 71, 51))
        self.current_battleround_number.setObjectName("current_battleround_number")
        self.turn_A = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_A.setGeometry(QtCore.QRect(30, 80, 201, 41))
        self.turn_A.setObjectName("turn_A")
        self.playerB_add_turn = QtWidgets.QPushButton(self.centralwidget)
        self.playerB_add_turn.setGeometry(QtCore.QRect(930, 120, 61, 61))
        self.playerB_add_turn.setObjectName("playerB_add_turn")
        self.turn_number_B = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_number_B.setGeometry(QtCore.QRect(850, 120, 81, 61))
        self.turn_number_B.setObjectName("turn_number_B")
        self.turn_B = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_B.setGeometry(QtCore.QRect(790, 80, 201, 41))
        self.turn_B.setObjectName("turn_B")
        self.playerB_subtract_turn = QtWidgets.QPushButton(self.centralwidget)
        self.playerB_subtract_turn.setGeometry(QtCore.QRect(790, 120, 61, 61))
        self.playerB_subtract_turn.setObjectName("playerB_subtract_turn")
        self.playerA_add_CP = QtWidgets.QPushButton(self.centralwidget)
        self.playerA_add_CP.setGeometry(QtCore.QRect(170, 250, 61, 61))
        self.playerA_add_CP.setObjectName("playerA_add_CP")
        self.CP_number_A = QtWidgets.QTextEdit(self.centralwidget)
        self.CP_number_A.setGeometry(QtCore.QRect(90, 250, 81, 61))
        self.CP_number_A.setObjectName("CP_number_A")
        self.CP_A = QtWidgets.QTextEdit(self.centralwidget)
        self.CP_A.setGeometry(QtCore.QRect(30, 210, 201, 41))
        self.CP_A.setObjectName("CP_A")
        self.playerA_subtract_CP = QtWidgets.QPushButton(self.centralwidget)
        self.playerA_subtract_CP.setGeometry(QtCore.QRect(30, 250, 61, 61))
        self.playerA_subtract_CP.setObjectName("playerA_subtract_CP")
        self.playerB_add_CP = QtWidgets.QPushButton(self.centralwidget)
        self.playerB_add_CP.setGeometry(QtCore.QRect(930, 250, 61, 61))
        self.playerB_add_CP.setObjectName("playerB_add_CP")
        self.CP_number_B = QtWidgets.QTextEdit(self.centralwidget)
        self.CP_number_B.setGeometry(QtCore.QRect(850, 250, 81, 61))
        self.CP_number_B.setObjectName("CP_number_B")
        self.CP_B = QtWidgets.QTextEdit(self.centralwidget)
        self.CP_B.setGeometry(QtCore.QRect(790, 210, 201, 41))
        self.CP_B.setObjectName("CP_B")
        self.playerB_subtract_CP = QtWidgets.QPushButton(self.centralwidget)
        self.playerB_subtract_CP.setGeometry(QtCore.QRect(790, 250, 61, 61))
        self.playerB_subtract_CP.setObjectName("playerB_subtract_CP")
        self.playerA_add_VP = QtWidgets.QPushButton(self.centralwidget)
        self.playerA_add_VP.setGeometry(QtCore.QRect(170, 390, 61, 61))
        self.playerA_add_VP.setObjectName("playerA_add_VP")
        self.VP_number_A = QtWidgets.QTextEdit(self.centralwidget)
        self.VP_number_A.setGeometry(QtCore.QRect(90, 390, 81, 61))
        self.VP_number_A.setObjectName("VP_number_A")
        self.VP_A = QtWidgets.QTextEdit(self.centralwidget)
        self.VP_A.setGeometry(QtCore.QRect(30, 350, 201, 41))
        self.VP_A.setObjectName("VP_A")
        self.playerA_subtract_VP = QtWidgets.QPushButton(self.centralwidget)
        self.playerA_subtract_VP.setGeometry(QtCore.QRect(30, 390, 61, 61))
        self.playerA_subtract_VP.setObjectName("playerA_subtract_VP")
        self.playerB_add_VP = QtWidgets.QPushButton(self.centralwidget)
        self.playerB_add_VP.setGeometry(QtCore.QRect(930, 390, 61, 61))
        self.playerB_add_VP.setObjectName("playerB_add_VP")
        self.VP_number_B = QtWidgets.QTextEdit(self.centralwidget)
        self.VP_number_B.setGeometry(QtCore.QRect(850, 390, 81, 61))
        self.VP_number_B.setObjectName("VP_number_B")
        self.VP_B = QtWidgets.QTextEdit(self.centralwidget)
        self.VP_B.setGeometry(QtCore.QRect(790, 350, 201, 41))
        self.VP_B.setObjectName("VP_B")
        self.playerB_subtract_VP = QtWidgets.QPushButton(self.centralwidget)
        self.playerB_subtract_VP.setGeometry(QtCore.QRect(790, 390, 61, 61))
        self.playerB_subtract_VP.setObjectName("playerB_subtract_VP")
        self.playerA = QtWidgets.QTextEdit(self.centralwidget)
        self.playerA.setGeometry(QtCore.QRect(30, 20, 271, 41))
        self.playerA.setObjectName("playerA")
        self.battle_tactic_A_1 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_A_1.setGeometry(QtCore.QRect(240, 140, 181, 21))
        self.battle_tactic_A_1.setObjectName("battle_tactic_A_1")
        self.grand_strategy_A = QtWidgets.QComboBox(self.centralwidget)
        self.grand_strategy_A.setGeometry(QtCore.QRect(40, 530, 221, 22))
        self.grand_strategy_A.setObjectName("grand_strategy_A")
        self.grand_strategy_B = QtWidgets.QComboBox(self.centralwidget)
        self.grand_strategy_B.setGeometry(QtCore.QRect(760, 530, 221, 22))
        self.grand_strategy_B.setObjectName("grand_strategy_B")
        self.turn_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_1.setGeometry(QtCore.QRect(490, 130, 51, 41))
        self.turn_1.setObjectName("turn_1")
        self.turn_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_2.setGeometry(QtCore.QRect(490, 200, 51, 41))
        self.turn_2.setObjectName("turn_2")
        self.turn_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_3.setGeometry(QtCore.QRect(490, 270, 51, 41))
        self.turn_3.setObjectName("turn_3")
        self.turn_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_4.setGeometry(QtCore.QRect(490, 340, 51, 41))
        self.turn_4.setObjectName("turn_4")
        self.turn_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_5.setGeometry(QtCore.QRect(490, 410, 51, 41))
        self.turn_5.setObjectName("turn_5")
        self.playerB = QtWidgets.QTextEdit(self.centralwidget)
        self.playerB.setGeometry(QtCore.QRect(720, 20, 271, 41))
        self.playerB.setObjectName("playerB")
        self.battle_tactic_A_2 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_A_2.setGeometry(QtCore.QRect(240, 210, 181, 21))
        self.battle_tactic_A_2.setObjectName("battle_tactic_A_2")
        self.battle_tactic_A_3 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_A_3.setGeometry(QtCore.QRect(240, 280, 181, 21))
        self.battle_tactic_A_3.setObjectName("battle_tactic_A_3")
        self.battle_tactic_A_4 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_A_4.setGeometry(QtCore.QRect(240, 350, 181, 21))
        self.battle_tactic_A_4.setObjectName("battle_tactic_A_4")
        self.battle_tactic_A_5 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_A_5.setGeometry(QtCore.QRect(240, 420, 181, 21))
        self.battle_tactic_A_5.setObjectName("battle_tactic_A_5")
        self.battle_tactic_B_2 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_B_2.setGeometry(QtCore.QRect(600, 210, 181, 21))
        self.battle_tactic_B_2.setObjectName("battle_tactic_B_2")
        self.battle_tactic_B_3 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_B_3.setGeometry(QtCore.QRect(600, 280, 181, 21))
        self.battle_tactic_B_3.setObjectName("battle_tactic_B_3")
        self.battle_tactic_B_4 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_B_4.setGeometry(QtCore.QRect(600, 350, 181, 21))
        self.battle_tactic_B_4.setObjectName("battle_tactic_B_4")
        self.battle_tactic_B_5 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_B_5.setGeometry(QtCore.QRect(600, 420, 181, 21))
        self.battle_tactic_B_5.setObjectName("battle_tactic_B_5")
        self.battle_tactic_B_1 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_B_1.setGeometry(QtCore.QRect(600, 140, 181, 21))
        self.battle_tactic_B_1.setObjectName("battle_tactic_B_1")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(460, 140, 16, 21))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(460, 210, 16, 21))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(460, 280, 16, 21))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(460, 350, 16, 21))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(460, 420, 16, 21))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(560, 140, 16, 21))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(560, 210, 16, 21))
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(560, 280, 16, 21))
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_9.setGeometry(QtCore.QRect(560, 350, 16, 21))
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_10.setGeometry(QtCore.QRect(560, 420, 16, 21))
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.grand_strategy = QtWidgets.QTextEdit(self.centralwidget)
        self.grand_strategy.setGeometry(QtCore.QRect(310, 520, 401, 31))
        self.grand_strategy.setObjectName("grand_strategy")
        self.checkBox_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_11.setGeometry(QtCore.QRect(1000, 530, 16, 21))
        self.checkBox_11.setTabletTracking(False)
        self.checkBox_11.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBox_11.setText("")
        self.checkBox_11.setIconSize(QtCore.QSize(16, 16))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 530, 16, 21))
        self.checkBox_12.setText("")
        self.checkBox_12.setObjectName("checkBox_12")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 120, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playerA_add_turn.setText(_translate("MainWindow", "+"))
        self.playerA_subtract_turn.setText(_translate("MainWindow", "-"))
        self.current_battleround_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Battle Round</span></p></body></html>"))
        self.turn_A.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Turn Nº</span></p></body></html>"))
        self.playerB_add_turn.setText(_translate("MainWindow", "+"))
        self.turn_B.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Turn Nº</span></p></body></html>"))
        self.playerB_subtract_turn.setText(_translate("MainWindow", "-"))
        self.playerA_add_CP.setText(_translate("MainWindow", "+"))
        self.CP_A.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">CP</span></p></body></html>"))
        self.playerA_subtract_CP.setText(_translate("MainWindow", "-"))
        self.playerB_add_CP.setText(_translate("MainWindow", "+"))
        self.CP_B.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">CP</span></p></body></html>"))
        self.playerB_subtract_CP.setText(_translate("MainWindow", "-"))
        self.playerA_add_VP.setText(_translate("MainWindow", "+"))
        self.VP_A.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Victory Points</span></p></body></html>"))
        self.playerA_subtract_VP.setText(_translate("MainWindow", "-"))
        self.playerB_add_VP.setText(_translate("MainWindow", "+"))
        self.VP_B.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Victory Points</span></p></body></html>"))
        self.playerB_subtract_VP.setText(_translate("MainWindow", "-"))
        self.playerA.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Player A</span></p></body></html>"))
        self.turn_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">1</span></p></body></html>"))
        self.turn_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">2</span></p></body></html>"))
        self.turn_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">3</span></p></body></html>"))
        self.turn_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">4</span></p></body></html>"))
        self.turn_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">5</span></p></body></html>"))
        self.playerB.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Player B</span></p></body></html>"))
        self.grand_strategy.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">GRAND STRATEGY</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
