# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #Battleround management
        self.current_battleround_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.current_battleround_text.setGeometry(QtCore.QRect(360, 20, 251, 41))
        self.current_battleround_text.setObjectName("current_battleround_text")
        self.current_battleround_number = QtWidgets.QLabel(self.centralwidget)
        self.current_battleround_number.setGeometry(QtCore.QRect(450, 60, 71, 51))
        self.current_battleround_number.setObjectName("current_battleround_number")

        #Player A turn management
        self.turn_A = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_A.setGeometry(QtCore.QRect(30, 80, 201, 41))
        self.turn_A.setObjectName("turn_A")
        self.turn_number_A = QtWidgets.QLabel(self.centralwidget)
        self.turn_number_A.setGeometry(QtCore.QRect(90, 120, 81, 61))
        self.turn_number_A.setObjectName("turn_number_A")
        self.playerA_add_turn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.addTurn_A())
        self.playerA_add_turn.setGeometry(QtCore.QRect(170, 120, 61, 61))
        self.playerA_add_turn.setObjectName("playerA_add_turn")
        self.playerA_subtract_turn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.subtractTurn_A())
        self.playerA_subtract_turn.setGeometry(QtCore.QRect(30, 120, 61, 61))
        self.playerA_subtract_turn.setObjectName("playerA_subtract_turn")

        # Player B turn management
        self.turn_B = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_B.setGeometry(QtCore.QRect(740, 80, 201, 41))
        self.turn_B.setObjectName("turn_B")
        self.turn_number_B = QtWidgets.QLabel(self.centralwidget)
        self.turn_number_B.setGeometry(QtCore.QRect(800, 120, 81, 61))
        self.turn_number_B.setObjectName("turn_number_B")
        self.playerB_add_turn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.addTurn_B("1"))
        self.playerB_add_turn.setGeometry(QtCore.QRect(880, 120, 61, 61))
        self.playerB_add_turn.setObjectName("playerB_add_turn")
        self.playerB_subtract_turn = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.subtractTurn_B())
        self.playerB_subtract_turn.setGeometry(QtCore.QRect(740, 120, 61, 61))
        self.playerB_subtract_turn.setObjectName("playerB_subtract_turn")

        # Player A CP management
        self.CP_A = QtWidgets.QTextEdit(self.centralwidget)
        self.CP_A.setGeometry(QtCore.QRect(30, 210, 201, 41))
        self.CP_A.setObjectName("CP_A")
        self.CP_number_A = QtWidgets.QLabel(self.centralwidget)
        self.CP_number_A.setGeometry(QtCore.QRect(90, 250, 81, 61))
        self.CP_number_A.setObjectName("CP_number_A")
        self.playerA_add_CP = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.addCP_A())
        self.playerA_add_CP.setGeometry(QtCore.QRect(170, 250, 61, 61))
        self.playerA_add_CP.setObjectName("playerA_add_CP")
        self.playerA_subtract_CP = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.subtractCP_A())
        self.playerA_subtract_CP.setGeometry(QtCore.QRect(30, 250, 61, 61))
        self.playerA_subtract_CP.setObjectName("playerA_subtract_CP")

        # Player B CP management
        self.CP_B = QtWidgets.QTextEdit(self.centralwidget)
        self.CP_B.setGeometry(QtCore.QRect(740, 210, 201, 41))
        self.CP_B.setObjectName("CP_B")
        self.CP_number_B = QtWidgets.QLabel(self.centralwidget)
        self.CP_number_B.setGeometry(QtCore.QRect(800, 250, 81, 61))
        self.CP_number_B.setObjectName("CP_number_B")
        self.playerB_add_CP = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.addCP_B())
        self.playerB_add_CP.setGeometry(QtCore.QRect(880, 250, 61, 61))
        self.playerB_add_CP.setObjectName("playerB_add_CP")
        self.playerB_subtract_CP = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.subtractCP_B())
        self.playerB_subtract_CP.setGeometry(QtCore.QRect(740, 250, 61, 61))
        self.playerB_subtract_CP.setObjectName("playerB_subtract_CP")

        # Player A VP management
        self.VP_A = QtWidgets.QTextEdit(self.centralwidget)
        self.VP_A.setGeometry(QtCore.QRect(30, 350, 201, 41))
        self.VP_A.setObjectName("VP_A")
        self.VP_number_A = QtWidgets.QLabel(self.centralwidget)
        self.VP_number_A.setGeometry(QtCore.QRect(90, 390, 81, 61))
        self.VP_number_A.setObjectName("VP_number_A")
        self.playerA_add_VP = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.addVP_A())
        self.playerA_add_VP.setGeometry(QtCore.QRect(170, 390, 61, 61))
        self.playerA_add_VP.setObjectName("playerA_add_VP")
        self.playerA_subtract_VP = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.subtractVP_A())
        self.playerA_subtract_VP.setGeometry(QtCore.QRect(30, 390, 61, 61))
        self.playerA_subtract_VP.setObjectName("playerA_subtract_VP")

        # Player B VP management
        self.VP_B = QtWidgets.QTextEdit(self.centralwidget)
        self.VP_B.setGeometry(QtCore.QRect(740, 350, 201, 41))
        self.VP_B.setObjectName("VP_B")
        self.VP_number_B = QtWidgets.QLabel(self.centralwidget)
        self.VP_number_B.setGeometry(QtCore.QRect(800, 390, 81, 61))
        self.VP_number_B.setObjectName("VP_number_B")
        self.playerB_add_VP = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.addVP_B())
        self.playerB_add_VP.setGeometry(QtCore.QRect(880, 390, 61, 61))
        self.playerB_add_VP.setObjectName("playerB_add_VP")
        self.playerB_subtract_VP = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.subtractVP_B())
        self.playerB_subtract_VP.setGeometry(QtCore.QRect(740, 390, 61, 61))
        self.playerB_subtract_VP.setObjectName("playerB_subtract_VP")

        self.playerA = QtWidgets.QTextEdit(self.centralwidget)
        self.playerA.setGeometry(QtCore.QRect(30, 20, 271, 41))
        self.playerA.setObjectName("playerA")
        self.battle_tactic_A_1 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_A_1.setGeometry(QtCore.QRect(240, 140, 181, 21))
        self.battle_tactic_A_1.setObjectName("battle_tactic_A_1")
        self.grand_strategy_A = QtWidgets.QComboBox(self.centralwidget)
        self.grand_strategy_A.setGeometry(QtCore.QRect(240, 510, 221, 22))
        self.grand_strategy_A.setObjectName("grand_strategy_A")
        self.grand_strategy_B = QtWidgets.QComboBox(self.centralwidget)
        self.grand_strategy_B.setGeometry(QtCore.QRect(510, 510, 221, 22))
        self.grand_strategy_B.setObjectName("grand_strategy_B")
        self.turn_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_1.setGeometry(QtCore.QRect(460, 130, 51, 41))
        self.turn_1.setObjectName("turn_1")
        self.turn_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_2.setGeometry(QtCore.QRect(460, 200, 51, 41))
        self.turn_2.setObjectName("turn_2")
        self.turn_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_3.setGeometry(QtCore.QRect(460, 270, 51, 41))
        self.turn_3.setObjectName("turn_3")
        self.turn_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_4.setGeometry(QtCore.QRect(460, 340, 51, 41))
        self.turn_4.setObjectName("turn_4")
        self.turn_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.turn_5.setGeometry(QtCore.QRect(460, 410, 51, 41))
        self.turn_5.setObjectName("turn_5")
        self.playerB = QtWidgets.QTextEdit(self.centralwidget)
        self.playerB.setGeometry(QtCore.QRect(670, 20, 271, 41))
        self.playerB.setObjectName("playerB")
        self.battle_tactic_A_2 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_A_2.setGeometry(QtCore.QRect(240, 210, 181, 21))
        self.battle_tactic_A_2.setObjectName("battle_tactic_A_2")
        self.battle_tactic_A_3 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_A_3.setGeometry(QtCore.QRect(240, 280, 181, 21))
        self.battle_tactic_A_3.setObjectName("battle_tactic_A_3")
        self.battle_tactic_A_4 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_A_4.setGeometry(QtCore.QRect(240, 350, 181, 21))
        self.battle_tactic_A_4.setObjectName("battle_tactic_A_4")
        self.battle_tactic_A_5 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_A_5.setGeometry(QtCore.QRect(240, 420, 181, 21))
        self.battle_tactic_A_5.setObjectName("battle_tactic_A_5")
        self.battle_tactic_B_2 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_B_2.setGeometry(QtCore.QRect(550, 210, 181, 21))
        self.battle_tactic_B_2.setObjectName("battle_tactic_B_2")
        self.battle_tactic_B_3 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_B_3.setGeometry(QtCore.QRect(550, 280, 181, 21))
        self.battle_tactic_B_3.setObjectName("battle_tactic_B_3")
        self.battle_tactic_B_4 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_B_4.setGeometry(QtCore.QRect(550, 350, 181, 21))
        self.battle_tactic_B_4.setObjectName("battle_tactic_B_4")
        self.battle_tactic_B_5 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_B_5.setGeometry(QtCore.QRect(550, 420, 181, 21))
        self.battle_tactic_B_5.setObjectName("battle_tactic_B_5")
        self.battle_tactic_B_1 = QtWidgets.QComboBox(self.centralwidget)
        self.battle_tactic_B_1.setGeometry(QtCore.QRect(550, 140, 181, 21))
        self.battle_tactic_B_1.setObjectName("battle_tactic_B_1")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(430, 140, 16, 21))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(430, 210, 16, 21))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(430, 280, 16, 21))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(430, 350, 16, 21))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(430, 420, 16, 21))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(530, 140, 16, 21))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(530, 210, 16, 21))
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(530, 280, 16, 21))
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_9.setGeometry(QtCore.QRect(530, 350, 16, 21))
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_10.setGeometry(QtCore.QRect(530, 420, 16, 21))
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.grand_strategy = QtWidgets.QTextEdit(self.centralwidget)
        self.grand_strategy.setGeometry(QtCore.QRect(290, 470, 401, 31))
        self.grand_strategy.setObjectName("grand_strategy")
        self.checkBox_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_11.setGeometry(QtCore.QRect(750, 510, 16, 21))
        self.checkBox_11.setTabletTracking(False)
        self.checkBox_11.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBox_11.setText("")
        self.checkBox_11.setIconSize(QtCore.QSize(16, 16))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_12.setGeometry(QtCore.QRect(210, 510, 16, 21))
        self.checkBox_12.setText("")
        self.checkBox_12.setObjectName("checkBox_12")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    #Battleround logic
    def battleround_num(self):
        if self.turn_number_A.text() == self.turn_number_B.text() or self.current_battleround_number.text() >= "5":
            pass
        elif self.turn_number_A.text() > str(eval(self.turn_number_B.text() + "+1")):
            pass
        elif self.turn_number_B.text() > str(eval(self.turn_number_A.text() + "+1")):
            pass
        else:
            add_battleround = (self.current_battleround_number.text() + "+1")
            hola = eval(add_battleround)
            self.current_battleround_number.setText(str(hola))

    #Turn management
    def addTurn_A(self):
        if self.turn_number_A.text() <= "4":
            add_1 = (self.turn_number_A.text() + "+1")
            addition = eval(add_1)
            self.turn_number_A.setText(str(addition))
            self.battleround_num()
        else:
            pass

    def subtractTurn_A(self):
        if self.turn_number_A.text() == "0":
            pass
        elif "0" < self.turn_number_A.text() <= "5":
            subtract_1 = (self.turn_number_A.text() + "-1")
            subtraction = eval(subtract_1)
            self.turn_number_A.setText(str(subtraction))

    def addTurn_B(self, pressed):
        if self.turn_number_B.text() <= "4":
            add_1 = (self.turn_number_B.text() + "+1")
            addition = eval(add_1)
            self.turn_number_B.setText(str(addition))
            self.battleround_num()
        else:
            pass

    def subtractTurn_B(self):
        if self.turn_number_B.text() == "0":
            pass
        elif "0" < self.turn_number_B.text() <= "5":
            subtract_1 = (self.turn_number_B.text() + "-1")
            subtraction = eval(subtract_1)
            self.turn_number_B.setText(str(subtraction))

    #CP management
    def addCP_A(self):
        add_cp = (self.CP_number_A.text() + "+1")
        cp_addition = eval(add_cp)
        self.CP_number_A.setText(str(cp_addition))

    def subtractCP_A(self):
        if self.CP_number_A.text() == "0":
            pass
        else:
            subtract_cp = (self.CP_number_A.text() + "-1")
            cp_subtraction = eval(subtract_cp)
            self.CP_number_A.setText(str(cp_subtraction))

    def addCP_B(self):
        add_cp = (self.CP_number_B.text() + "+1")
        cp_addition = eval(add_cp)
        self.CP_number_B.setText(str(cp_addition))

    def subtractCP_B(self):
        if self.CP_number_B.text() == "0":
            pass
        else:
            subtract_cp = (self.CP_number_B.text() + "-1")
            cp_subtraction = eval(subtract_cp)
            self.CP_number_B.setText(str(cp_subtraction))

    #VP management
    def addVP_A(self):
        add_vp = (self.VP_number_A.text() + "+1")
        vp_addition = eval(add_vp)
        self.VP_number_A.setText(str(vp_addition))

    def subtractVP_A(self):
        if self.VP_number_A.text() == "0":
            pass
        else:
            subtract_vp = (self.VP_number_A.text() + "-1")
            vp_subtraction = eval(subtract_vp)
            self.VP_number_A.setText(str(vp_subtraction))

    def addVP_B(self):
        add_vp = (self.VP_number_B.text() + "+1")
        vp_addition = eval(add_vp)
        self.VP_number_B.setText(str(vp_addition))

    def subtractVP_B(self):
        if self.VP_number_B.text() == "0":
            pass
        else:
            subtract_vp = (self.VP_number_B.text() + "-1")
            vp_subtraction = eval(subtract_vp)
            self.VP_number_B.setText(str(vp_subtraction))




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Warhammer_AoS_Game_Display"))
        self.playerA_add_turn.setText(_translate("MainWindow", "+"))
        self.playerA_subtract_turn.setText(_translate("MainWindow", "-"))
        self.current_battleround_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Battle Round</span></p></body></html>"))
        self.turn_A.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Turn Nº</span></p></body></html>"))
        self.playerB_add_turn.setText(_translate("MainWindow", "+"))
        self.turn_B.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Turn Nº</span></p></body></html>"))
        self.playerB_subtract_turn.setText(_translate("MainWindow", "-"))
        self.playerA_add_CP.setText(_translate("MainWindow", "+"))
        self.CP_A.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">CP</span></p></body></html>"))
        self.playerA_subtract_CP.setText(_translate("MainWindow", "-"))
        self.playerB_add_CP.setText(_translate("MainWindow", "+"))
        self.CP_B.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">CP</span></p></body></html>"))
        self.playerB_subtract_CP.setText(_translate("MainWindow", "-"))
        self.playerA_add_VP.setText(_translate("MainWindow", "+"))
        self.VP_A.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Victory Points</span></p></body></html>"))
        self.playerA_subtract_VP.setText(_translate("MainWindow", "-"))
        self.playerB_add_VP.setText(_translate("MainWindow", "+"))
        self.VP_B.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Victory Points</span></p></body></html>"))
        self.playerB_subtract_VP.setText(_translate("MainWindow", "-"))
        self.playerA.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Player A</span></p></body></html>"))
        self.turn_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">1</span></p></body></html>"))
        self.turn_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">2</span></p></body></html>"))
        self.turn_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">3</span></p></body></html>"))
        self.turn_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">4</span></p></body></html>"))
        self.turn_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">5</span></p></body></html>"))
        self.playerB.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Player B</span></p></body></html>"))
        self.grand_strategy.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">GRAND STRATEGY</span></p></body></html>"))

        self.current_battleround_number.setText(_translate("MainWindow", "0"))
        self.turn_number_A.setText(_translate("MainWindow", "0"))
        self.turn_number_B.setText(_translate("MainWindow", "0"))
        self.CP_number_A.setText(_translate("MainWindow", "0"))
        self.CP_number_B.setText(_translate("MainWindow", "0"))
        self.VP_number_A.setText(_translate("MainWindow", "0"))
        self.VP_number_B.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
